name: "Adds sized label to pull request"

on: [pull_request]

jobs:
    labeler:
        permissions:
            pull-requests: write
            contents: read
            issues: write
        runs-on: ubuntu-latest
        name: Label the PR size
        steps:
            - uses: codelytv/pr-size-labeler@v1.10.2
              with:
                  xs_max_size: "100"
                  s_max_size: "200"
                  m_max_size: "500"
                  l_max_size: "1000"
                  fail_if_xl: "false"
                  message_if_xl: "This PR is so big! Please, split it ðŸ˜Š"
                  files_to_ignore: "package-lock.json *.lock"
                  github_api_url: "https://api.github.com"
